set(SRC_FILES
    Arknights/App.cpp
    Arknights/Entity/Enemy.cpp
    Arknights/Map/Operation.cpp
    Arknights/Map/StageRepository.cpp
    Arknights/Map/StageFactory.cpp
    Arknights/Entity/Operator.cpp
    Arknights/Scenes/Scene.cpp
    Arknights/Scenes/LoginScene.cpp
    Arknights/Scenes/LobbyScene.cpp
    Arknights/Scenes/StageSelectScene.cpp
    Arknights/Scenes/LoadingScene.cpp
    Arknights/Scenes/GameScene.cpp
    Arknights/Core/SceneManager.cpp
    Arknights/UI/Button.cpp
)

set(INCLUDE_FILES
    Arknights/App.hpp
    Arknights/Entity/Enemy.hpp
    Arknights/Map/Operation.hpp
    Arknights/Map/StageDefinition.hpp
    Arknights/Map/StageRepository.hpp
    Arknights/Map/StageFactory.hpp
    Arknights/UI/HealthBar.hpp
    Arknights/Entity/Operator.hpp
    Arknights/Scenes/Scene.hpp
    Arknights/Scenes/LoginScene.hpp
    Arknights/Scenes/LobbyScene.hpp
    Arknights/Scenes/StageSelectScene.hpp
    Arknights/Scenes/LoadingScene.hpp
    Arknights/Scenes/GameScene.hpp
    Arknights/Core/SceneManager.hpp
    Arknights/UI/Button.hpp
)

set(TEST_FILES
)
