set(SRC_FILES
    Arknights/App.cpp
    Arknights/Enemy.cpp
    Arknights/EnemyPool.cpp
    Arknights/Operation.cpp
    Arknights/Operator.cpp
    Arknights/Scenes/Scene.cpp
    Arknights/Scenes/LoginScene.cpp
    Arknights/Scenes/LobbyScene.cpp
    Arknights/Scenes/GameScene.cpp
    Arknights/Core/SceneManager.cpp
    Arknights/UI/Button.cpp
)

set(INCLUDE_FILES
    Arknights/App.hpp
    Arknights/Enemy.hpp
    Arknights/EnemyPool.hpp
    Arknights/Operation.hpp
    Arknights/Operator.hpp
    Arknights/WaveManager.hpp
    Arknights/Scenes/Scene.hpp
    Arknights/Scenes/LoginScene.hpp
    Arknights/Scenes/LobbyScene.hpp
    Arknights/Scenes/GameScene.hpp
    Arknights/Core/SceneManager.hpp
    Arknights/UI/Button.hpp
)

set(TEST_FILES
)
